### ISSUE TITLE
Workers need heartbeating capability

### ISSUE THREAD

**Issue by NXdriveBeta** [NXdriveBeta/container-workers#2]
In order to have some idea of a worker, we need a worker to report its state at certain intervals. Therefore, we decide to create a queue called "worker-heartbeating". Each worker is required to report its liveness to this committed queue.

**Comment by HaoPengNXDrive** [comment]
Now workers will start a thread aside their working loop and will send heartbeat message every few minutes. 

There is a heartbeat receiver console project inside storage provider solution. It can receive messages from all workers.
